default_install_hook_types: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        args:
          - "--pytest-test-first"
    -   id: requirements-txt-fixer
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    description: Run isort to add import headers, and sort imports
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
    description: Run black to format Python code
  - id: hadolint
    name: Lint Dockerfiles
    entry: hadolint
    description: Run hadolint to lint Dockerfiles
    language: system
    types: ["dockerfile"]
- repo: https://github.com/zahorniak/pre-commit-circleci.git
  rev: v0.6
  hooks:
    - id: circleci_validate
      description: Validate `.circleci/config.yml` file
# - repo: https://github.com/sourcery-ai/sourcery
#   rev: v1.2.0
#   hooks:
#     - id: sourcery
#       # The best way to use Sourcery in a pre-commit hook:
#       # * review only changed lines:
#       # * omit the summary
#       args: [--diff=git diff HEAD, --no-summary]
#       # to automatically apply the changes
#       # args: [--diff=git diff HEAD, --fix, --no-summary]
#       name: sourcery
#       types: [python]
#       stages: [push]
#       description: Run sourcery to suggest refactorings for Python code, using Google style guide